main: org.nyanneko0113.discord_join.Main
version: '${project.version}'
name: Discord_Join

commands:
  discord_whitelist:
    description: ホワイトリストを設定するコマンド
    permission: nyanneko0113.discord_join.commands.discord_whitelist